# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generate_sub_coordinates <- function(x, n_subs = 3L) {
    .Call('_grimon_generate_sub_coordinates', PACKAGE = 'grimon', x, n_subs)
}

#' @export
construct_segment_matrix <- function(x) {
    .Call('_grimon_construct_segment_matrix', PACKAGE = 'grimon', x)
}

#' @export
norm_matrix <- function(x, z_idx, scale, shift) {
    .Call('_grimon_norm_matrix', PACKAGE = 'grimon', x, z_idx, scale, shift)
}

#' @export
optimize_coordinates <- function(x, z_idx, segment_mat, maxiter, T, alpha, score_function, to_norm, norm_scale, norm_shift, to_rotate = TRUE, to_flip = TRUE, to_shift = TRUE, progress = FALSE) {
    .Call('_grimon_optimize_coordinates', PACKAGE = 'grimon', x, z_idx, segment_mat, maxiter, T, alpha, score_function, to_norm, norm_scale, norm_shift, to_rotate, to_flip, to_shift, progress)
}

#' @export
wide_to_long <- function(x, z_interval) {
    .Call('_grimon_wide_to_long', PACKAGE = 'grimon', x, z_interval)
}

